### ISSUE TITLE
Cant Pull the image

### ISSUE THREAD

**Issue by PDXUser** [samcro1967/docker-compose-ports-dump#1]
I saw your post on Reddit - your compose file needs a "Services" header for it to work, but also, when trying to pull the image, it's restricted:

```docker compose up -d
[+] Running 0/1
 ⠿ dcpd Error                                                                                                                                                         0.2s
Error response from daemon: Head "https://ghcr.io/v2/samcro1967/docker_compose_ports_dump/manifests/latest": denied
```
So, at this point, no way to check your software out.

**Comment by samcro1967** [comment]
Didn't realize packages defaulted to private.  It is now set to public so you should be able to pull it now.

**Comment by PDXUser** [comment]
Nope, still can not.  I can pull from other github sources though so I don't think it's my account?  
Same error and message.   Any chance of putting this on (*shudders)   Docker hub so I can maybe pull it from there?

**Comment by samcro1967** [comment]
I am able to pull the image anonymously without issue.  Not sure why you are not able to, but everything seems to be setup correctly and is working as expected for me.   Looking into adding it to Docker Hub also.

user@hostname1:~/Documents/Docker$ docker logout ghcr.io
Removing login credentials for ghcr.io
user@hostname1:~/Documents/Docker$ docker pull ghcr.io/samcro1967/docker-compose-ports-dump:latest
latest: Pulling from samcro1967/docker-compose-ports-dump
efb124c083f2: Pull complete
b81e0d862760: Pull complete
d0f59184f0b9: Pull complete
af23b7546513: Pull complete
c56105954327: Pull complete
438a18a61d92: Pull complete
4f4fb700ef54: Pull complete
10a40d67cdfd: Pull complete
01999cdbf177: Pull complete
Digest: sha256:b71d5cbb3afdcf393dd87e8e3ae4b55e780fb4f7b2a24b2b67565a68abd3302f
Status: Downloaded newer image for ghcr.io/samcro1967/docker-compose-ports-dump:latest
ghcr.io/samcro1967/docker-compose-ports-dump:latest
user@hostname1:~/Documents/Docker$

**Comment by samcro1967** [comment]
@PDXUser Try this:
docker pull osuhickeys/docker-compose-ports-dump:latest

**Comment by PDXUser** [comment]
I was able to pull the image using your image: osuhickeys/docker-compose-ports-dump:latest from the compose and have it running now. Just not seeing my directory, I'm certain I mismapped it, but feel free to close this.
